-- Add a new comment
-- Add another comment
SELECT  DISTINCT CASE
       WHEN P1.PORTAL_LABEL IS NULL THEN ''
       WHEN P1.PORTAL_LABEL = 'Root' THEN ''
              ELSE P1.PORTAL_LABEL + ' > ' END +
CASE WHEN P2.PORTAL_LABEL IS NULL THEN '' WHEN P2.PORTAL_LABEL = 'Root' THEN '' ELSE P2.PORTAL_LABEL + ' > ' END + CASE
WHEN P3.PORTAL_LABEL IS NULL THEN '' WHEN P3.PORTAL_LABEL = 'Root' THEN '' ELSE P3.PORTAL_LABEL + ' > ' END + CASE WHEN
P4.PORTAL_LABEL IS NULL THEN '' WHEN P4.PORTAL_LABEL = 'Root' THEN '' ELSE P4.PORTAL_LABEL + ' > ' END + CASE WHEN
P5.PORTAL_LABEL IS NULL THEN '' WHEN P5.PORTAL_LABEL = 'Root' THEN '' ELSE P5.PORTAL_LABEL + ' > ' END + CASE WHEN
P6.PORTAL_LABEL IS NULL THEN '' WHEN P6.PORTAL_LABEL = 'Root' THEN '' ELSE P6.PORTAL_LABEL + ' > ' END + CASE WHEN
P7.PORTAL_LABEL IS NULL THEN '' WHEN P7.PORTAL_LABEL = 'Root' THEN '' ELSE P7.PORTAL_LABEL + ' > ' END Navigation
, P7.PORTAL_OBJNAME
, M.MENUNAME MenuName
, M.BARNAME
, M.ITEMNAME BarItemName
, M.ITEMLABEL ItemLabel
, M.PNLGRPNAME Component
, PG.ITEMNAME PNLITEMNAME
, PG.PNLNAME PageName
, PG.ITEMLABEL PageLabel
, A.ACTIONS
, CASE A.ACTIONS  WHEN 0 THEN  'None' WHEN 1 THEN 'Add' WHEN 2 THEN 'U/D' WHEN 3 THEN 'Add, U/D' WHEN 4 THEN 'U/D+' WHEN 5 THEN 'Add, U/D+' WHEN 6 THEN 'U/D, U/D+' WHEN 7 THEN 'Add, U/D, U/D+' WHEN 8 THEN 'Corr' WHEN 9 THEN 'Add, Corr' WHEN 10 THEN 'U/D, Corr' WHEN 11 THEN 'Add, U/D, Corr'
        WHEN 12 THEN 'U/D+, Corr' WHEN 13 THEN 'Add, U/D+, Corr' WHEN 14 THEN 'U/D, U/D+, Corr' WHEN 15 THEN 'Add, U/D, U/D+, Corr' WHEN 128 THEN 'Data Entry' END AS AVAILABLE_ACTIONS
,' '
, CASE   WHEN AI.DISPLAYONLY IS NULL THEN  ' '  WHEN AI.DISPLAYONLY = 0 THEN  ' '  WHEN AI.DISPLAYONLY = 1 THEN  'X' END AS V
, CASE WHEN AI.AUTHORIZEDACTIONS IS NULL THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 1 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 2 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 3 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 4 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 5 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 6 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 7 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 8 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 9 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 10 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 11 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 12 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 13 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 14 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 15 THEN 'X' END AS AD
,CASE WHEN AI.AUTHORIZEDACTIONS IS NULL THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 1 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 2 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 3 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 4 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 5 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 6 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 7 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 8 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 9 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 10 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 11 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 12 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 13 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 14 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 15 THEN 'X' END AS UD
,CASE WHEN AI.AUTHORIZEDACTIONS IS NULL THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 1 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 2 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 3 THEN ' '
        WHEN AI.AUTHORIZEDACTIONS = 4 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 5 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 6 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 7 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 8 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 9 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 10 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 11 THEN ' '
        WHEN AI.AUTHORIZEDACTIONS = 12 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 13 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 14 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 15 THEN 'X' END AS AU
,CASE WHEN AI.AUTHORIZEDACTIONS IS NULL THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 1 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 2 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 3 THEN ' '
        WHEN AI.AUTHORIZEDACTIONS = 4 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 5 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 6 THEN ' ' WHEN AI.AUTHORIZEDACTIONS = 7 THEN ' '
        WHEN AI.AUTHORIZEDACTIONS = 8 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 9 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 10 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 11 THEN 'X'
        WHEN AI.AUTHORIZEDACTIONS = 12 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 13 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 14 THEN 'X' WHEN AI.AUTHORIZEDACTIONS = 15 THEN 'X' END AS C
, CASE P1.PORTAL_REFTYPE WHEN 'F' THEN '0' WHEN 'C' THEN '1' END + CASE WHEN P1.PORTAL_SEQ_NUM IS NULL THEN '' ELSE
RIGHT(REPLICATE('0', 4) + CAST(P1.PORTAL_SEQ_NUM AS VARCHAR), 4)
 END + P1.PORTAL_LABEL + CASE P2.PORTAL_REFTYPE WHEN 'F' THEN '0' WHEN 'C' THEN '1' END + CASE WHEN
P2.PORTAL_SEQ_NUM IS NULL THEN '' ELSE  RIGHT(REPLICATE('0', 4) + CAST(P2.PORTAL_SEQ_NUM AS VARCHAR), 4)
 END + P2.PORTAL_LABEL + CASE P3.PORTAL_REFTYPE WHEN 'F' THEN '0' WHEN 'C' THEN '1' END + CASE WHEN
P3.PORTAL_SEQ_NUM IS NULL THEN '' ELSE RIGHT(REPLICATE('0', 4) + CAST(P3.PORTAL_SEQ_NUM AS VARCHAR), 4)
 END + P3.PORTAL_LABEL + CASE P4.PORTAL_REFTYPE WHEN 'F' THEN '0' WHEN 'C' THEN '1' END + CASE WHEN
P4.PORTAL_SEQ_NUM IS NULL THEN '' ELSE RIGHT(REPLICATE('0', 4) + CAST(P4.PORTAL_SEQ_NUM AS VARCHAR), 4)
 END + P4.PORTAL_LABEL + CASE P5.PORTAL_REFTYPE WHEN 'F' THEN '0' WHEN 'C' THEN '1' END + CASE WHEN
P5.PORTAL_SEQ_NUM IS NULL THEN '' ELSE RIGHT(REPLICATE('0', 4) + CAST(P5.PORTAL_SEQ_NUM AS VARCHAR), 4)
 END + P5.PORTAL_LABEL + CASE P6.PORTAL_REFTYPE WHEN 'F' THEN '0' WHEN 'C' THEN '1' END + CASE WHEN
P6.PORTAL_SEQ_NUM IS NULL THEN '' ELSE RIGHT(REPLICATE('0', 4) + CAST(P6.PORTAL_SEQ_NUM AS VARCHAR), 4)
END + P6.PORTAL_LABEL + CASE P7.PORTAL_REFTYPE WHEN 'F' THEN '0' WHEN 'C' THEN '1' END + CASE WHEN
P7.PORTAL_SEQ_NUM IS NULL THEN '' ELSE RIGHT(REPLICATE('0', 4) + CAST(P7.PORTAL_SEQ_NUM AS VARCHAR), 4)
 END + P7.PORTAL_LABEL

FROM          PSMENUITEM M
JOIN          PSPRSMDEFN P7 ON P7.PORTAL_URI_SEG1 = M.MENUNAME  AND P7.PORTAL_URI_SEG2 = M.PNLGRPNAME
JOIN          PSPNLGRPDEFN A             ON A.PNLGRPNAME = M.PNLGRPNAME
JOIN          PSPNLGROUP PG ON PG.PNLGRPNAME = A.PNLGRPNAME
LEFT JOIN     PSPRSMDEFN P6 ON P6.PORTAL_NAME = P7.PORTAL_NAME AND P6.PORTAL_OBJNAME = P7.PORTAL_PRNTOBJNAME
LEFT JOIN     PSPRSMDEFN P5 ON P5.PORTAL_NAME = P6.PORTAL_NAME AND P5.PORTAL_OBJNAME = P6.PORTAL_PRNTOBJNAME
LEFT JOIN     PSPRSMDEFN P4 ON P4.PORTAL_NAME = P5.PORTAL_NAME AND P4.PORTAL_OBJNAME = P5.PORTAL_PRNTOBJNAME
LEFT JOIN     PSPRSMDEFN P3 ON P3.PORTAL_NAME = P4.PORTAL_NAME AND P3.PORTAL_OBJNAME = P4.PORTAL_PRNTOBJNAME
LEFT JOIN     PSPRSMDEFN P2 ON P2.PORTAL_NAME = P3.PORTAL_NAME AND P2.PORTAL_OBJNAME = P3.PORTAL_PRNTOBJNAME
LEFT JOIN     PSPRSMDEFN P1 ON P1.PORTAL_NAME = P2.PORTAL_NAME AND P1.PORTAL_OBJNAME = P2.PORTAL_PRNTOBJNAME
LEFT JOIN     PSAUTHITEM AI ON AI.MENUNAME = M.MENUNAME AND AI.BARNAME = M.BARNAME AND AI.BARITEMNAME = M.ITEMNAME AND AI.PNLITEMNAME = PG.ITEMNAME
WHERE   P7.PORTAL_LABEL <> ' '
   AND (P1.PORTAL_NAME = 'EMPLOYEE'
              OR P2.PORTAL_NAME = 'EMPLOYEE'
              OR P4.PORTAL_NAME = 'EMPLOYEE'
              OR P5.PORTAL_NAME = 'EMPLOYEE'
              OR P6.PORTAL_NAME = 'EMPLOYEE'
              OR P7.PORTAL_NAME = 'EMPLOYEE')
   AND (P1.PORTAL_PRNTOBJNAME = 'PORTAL_ROOT_OBJECT'
              OR P2.PORTAL_PRNTOBJNAME = 'PORTAL_ROOT_OBJECT'
              OR P3.PORTAL_PRNTOBJNAME = 'PORTAL_ROOT_OBJECT'
              OR P4.PORTAL_PRNTOBJNAME = 'PORTAL_ROOT_OBJECT'
              OR P5.PORTAL_PRNTOBJNAME = 'PORTAL_ROOT_OBJECT'
              OR P6.PORTAL_PRNTOBJNAME = 'PORTAL_ROOT_OBJECT'
              OR P7.PORTAL_PRNTOBJNAME = 'PORTAL_ROOT_OBJECT')
    and AI.CLASSID = 'UTHCPEB1000'
order by 19;
